[package]
name = "bus_notification_app"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"
notify-rust = "4.9.0"
serde_json = "1.0"
dotenv = "0.15.0"
