name: Bus Tracker

on:
  schedule:
    - cron: '30 8 * * 1-5'
  workflow_dispatch:

jobs:
  run-bus-tracker:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    env:
      LAT: ${{ secrets.LAT }}
      LNG: ${{ secrets.LNG }}
      RADIUS: ${{ secrets.RADIUS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          cache: true

      - name: Cache built binary
        uses: actions/cache@v3
        with:
          path: target/release/bus_notification_app
          key: rust-binary-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-binary-${{ runner.os }}-

      - name: Check if binary exists
        id: check_binary
        run: |
          if [ -f target/release/bus_notification_app ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Build project (if needed)
        if: env.exists == 'false'
        run: cargo build --release

      - name: Run the Bus Tracker script
        run: ./target/release/bus_notification_app
