name: Bus Tracker

on:
  schedule:
    - cron: '30 7 * * 1-5'
  workflow_dispatch:

jobs:
  run-bus-tracker:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      LAT: ${{ secrets.LAT }}
      LNG: ${{ secrets.LNG }}
      RADIUS: ${{ secrets.RADIUS }}
      BUS_STOPS: ${{ secrets.BUS_STOPS }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      # Cache Rust dependencies (Cargo registry and git dependencies) using default GitHub cache behavior
      - name: Cache Cargo registry and git
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: rust-deps-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-deps-${{ runner.os }}-

      # Build the project and the binary
      - name: Build project
        run: cargo build --release

      # Run the Bus Tracker script (use the built binary)
      - name: Run the Bus Tracker script
        run: ./target/release/bus_notification_app
