name: Bus Tracker

on:
  schedule:
    - cron: '30 8 * * 1-5'
  workflow_dispatch:

jobs:
  run-bus-tracker:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1.6.0

      - name: Install dependencies
        run: |
          cargo install

      - name: Run the Bus Tracker script
        run: |
          cargo run
