name: Bus Tracker

on:
  schedule:
    - cron: '30 8 * * 1-5'
  workflow_dispatch:

jobs:
  run-bus-tracker:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    env:
      LAT: ${{ secrets.LAT }}
      LNG: ${{ secrets.LNG }}
      RADIUS: ${{ secrets.RADIUS }}
      BUS_STOPS: ${{ secrets.BUS_STOPS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      # Cache Rust dependencies and the target directory (where the binary is built)
      - name: Cache Cargo registry and target
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: rust-deps-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-deps-${{ runner.os }}-

      # Check if binary exists (to skip build if already built and cached)
      - name: Check if binary exists
        id: check_binary
        run: |
          if [ -f target/release/bus_notification_app ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      # Build project only if the binary doesn't exist
      - name: Build project (if needed)
        if: env.exists == 'false'
        run: cargo build --release

      # Run the Bus Tracker script (use the built binary)
      - name: Run the Bus Tracker script
        run: ./target/release/bus_notification_app
